/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Specs used as a sample for the generator.
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.models

import com.squareup.moshi.Json

/**
 *
 * @property enumProperty
 * @property stringProperty
 */
data class PropertyModel(
    @Json(name = "enum_property") @field:Json(name = "enum_property") var enumProperty: PropertyModel.EnumPropertyEnum? = null,
    @Json(name = "string_property") @field:Json(name = "string_property") var stringProperty: String? = null
) {
    /**
     *
     * Values: VALUE2, VALUE1
     */
    enum class EnumPropertyEnum(val value: String) {
        @Json(name = "VALUE2") VALUE2("VALUE2"),
        @Json(name = "VALUE1") VALUE1("VALUE1")
    }
}
