/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Specs used as a sample for the generator.
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.apis

import com.yelp.codegen.generatecodesamples.models.EmptyModel
import com.yelp.codegen.generatecodesamples.models.PropertyModel
import io.reactivex.Single
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface ResourceApi {
    /**
     * Just an empty endpoint
     * The endpoint is owned by generatecodesamples service owner
     */
    @Headers(
            "X-Operation-ID: get_empty_endpoint"
    )
    @GET("/empty_endpoint")
    fun getEmptyEndpoint(): Single<EmptyModel>

    /**
     * Just a simple endpoint
     * The endpoint is owned by generatecodesamples service owner
     * @param propertyFormat (required)
     */
    @Headers(
            "X-Operation-ID: get_property_endpoint"
    )
    @GET("/property_endpoint/{property_format}")
    fun getPropertyEndpoint(
        @retrofit2.http.Path("property_format") propertyFormat: String
    ): Single<PropertyModel>
}
