/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Swagger Petstore
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.models

import com.squareup.moshi.Json

/**
 * A Category used to group pets
 * @property id Unique ID of the Category
 * @property name Name of this category
 */
data class Category(
    @Json(name = "id") @field:Json(name = "id") var id: Long? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null
)
