/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * This is a specific type of `animal`: a `dog`
 * @property name
 * @property classification
 * @property type
 * @property size
 */
@JsonClass(generateAdapter = true)
data class Dog(
    @Json(name = "size") @field:Json(name = "size") var size: Dog.SizeEnum,
    @Json(name = "name") @field:Json(name = "name") override var name: String,
    @Json(name = "type") @field:Json(name = "type") override var type: String,
    @Json(name = "classification") @field:Json(name = "classification") override var classification: Animal.ClassificationEnum? = null
) : Animal(name = name, classification = classification, type = type) {
    /**
     * Values: SMALL, MEDIUM, LARGE
     */
    @JsonClass(generateAdapter = false)
    enum class SizeEnum(val value: String) {
        @Json(name = "small") SMALL("small"),
        @Json(name = "medium") MEDIUM("medium"),
        @Json(name = "large") LARGE("large")
    }
}
