/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 * API Version:  1.1.0
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import org.threeten.bp.LocalDate
import org.threeten.bp.ZonedDateTime

/**
 * @property dateProperty
 * @property datetimeProperty
 * @property enumProperty
 */
@Serializable
data class FormatResponses(
  @SerialName("date_property") var dateProperty: LocalDate? = null,
  @SerialName("datetime_property") var datetimeProperty: ZonedDateTime? = null,
  @SerialName("enum_property") var enumProperty: FormatResponses.EnumPropertyEnum? = null

) {
  /**
   * Values: VALUE1, VALUE2
   */
  @Serializable
  enum class EnumPropertyEnum(val value: String) {
    VALUE1("VALUE1"),
    VALUE2("VALUE2")
  }
}
