/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.models

import kotlinx.datetime.Instant
import kotlinx.datetime.LocalDate
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @property dateProperty
 * @property datetimeProperty
 * @property enumProperty
 */
@Serializable
data class FormatResponses(
    @SerialName("date_property") var dateProperty: LocalDate? = null,
    @SerialName("datetime_property") var datetimeProperty: Instant? = null,
    @SerialName("enum_property") var enumProperty: FormatResponses.EnumPropertyEnum? = null
) {
    /**
     * Values: VALUE1, VALUE2
     */
    @Serializable
    enum class EnumPropertyEnum() {
        @SerialName("VALUE1") VALUE1,
        @SerialName("VALUE2") VALUE2
    }
}
