/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 * API Version:  1.1.0
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @property noXmodelNoTitle
 */
@Serializable
data class InlineResponse200(
  @SerialName("no_xmodel_no_title") var noXmodelNoTitle: InlineResponse200.NoXmodelNoTitleEnum? = null

) {
  /**
   * Values: VAL1, VAL2
   */
  @Serializable
  enum class NoXmodelNoTitleEnum(val value: String) {
    VAL1("val1"),
    VAL2("val2")
  }
}
