/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * This is a base class of `animal`. Created to verify that multiple parents are properly dealt with
 * @property name
 */
@JsonClass(generateAdapter = true)
data class LivingThing(
    @Json(name = "name") @field:Json(name = "name") var name: String
)
