/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property titleOnly
 */
@JsonClass(generateAdapter = true)
data class ModelWithOnlyTitle(
  @Json(name = "title_only") @field:Json(name = "title_only") var titleOnly: ModelWithOnlyTitle.TitleOnlyEnum? = null
) {
  /**
   * Values: VAL1, VAL2
   */
  @JsonClass(generateAdapter = false)
  enum class TitleOnlyEnum(val value: String) {
    @Json(name = "val1") VAL1("val1"),
    @Json(name = "val2") VAL2("val2")
  }
}
