/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @property xmodelOnly
 */
@Serializable
data class ModelWithOnlyXModel(
    @SerialName("xmodel_only") var xmodelOnly: ModelWithOnlyXModel.XmodelOnlyEnum? = null
) {
    /**
     * Values: VAL1, VAL2
     */
    @Serializable
    enum class XmodelOnlyEnum() {
        @SerialName("val1") VAL1,
        @SerialName("val2") VAL2
    }
}
