/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @property xmodelAndTitle
 */
@Serializable
data class ModelWithXModelAndTitle(
    @SerialName("xmodel_and_title") var xmodelAndTitle: ModelWithXModelAndTitle.XmodelAndTitleEnum? = null
) {
    /**
     * Values: VAL1, VAL2
     */
    @Serializable
    enum class XmodelAndTitleEnum() {
        @SerialName("val1") VAL1,
        @SerialName("val2") VAL2
    }
}
