/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 * API Version:  1.1.0
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import java.math.BigDecimal

/**
 * @property numberMap
 * @property objectMap
 * @property stringMap
 */
@Serializable
data class PropertyMap(
  @SerialName("number_map") var numberMap: Map<String, BigDecimal>? = null,
  @SerialName("object_map") var objectMap: Map<String, Any?>? = null,
  @SerialName("string_map") var stringMap: Map<String, String>? = null

)
