/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * This is a specific type of `animal`: a `snake`
 * @property name
 * @property classification
 * @property type
 */
@JsonClass(generateAdapter = true)
data class Snake(
    @Json(name = "name") @field:Json(name = "name") override var name: String,
    @Json(name = "type") @field:Json(name = "type") override var type: String,
    @Json(name = "classification") @field:Json(name = "classification") override var classification: Animal.ClassificationEnum? = null
) : Animal(name = name, classification = classification, type = type) {
    /**
     * Values: AMPHIBIAN, BIRD, FISH, INSECT, MAMMAL, REPTILE
     */
    @JsonClass(generateAdapter = false)
    enum class ClassificationEnum(val value: String) {
        @Json(name = "amphibian") AMPHIBIAN("amphibian"),
        @Json(name = "bird") BIRD("bird"),
        @Json(name = "fish") FISH("fish"),
        @Json(name = "insect") INSECT("insect"),
        @Json(name = "mammal") MAMMAL("mammal"),
        @Json(name = "reptile") REPTILE("reptile")
    }
}
