/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
* Values: VALUE1,VALUE2
*/
@Serializable
enum class TopLevelEnum() {
    @SerialName("TOP_LEVEL_VALUE1") VALUE1,
    @SerialName("TOP_LEVEL_VALUE2") VALUE2
}
