/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal

/**
 *
 * @property booleanProperty
 * @property integerProperty
 * @property numberProperty
 * @property stringProperty
 */
@JsonClass(generateAdapter = true)
data class TypeResponses(
    @Json(name = "boolean_property") @field:Json(name = "boolean_property") var booleanProperty: Boolean? = null,
    @Json(name = "integer_property") @field:Json(name = "integer_property") var integerProperty: Int? = null,
    @Json(name = "number_property") @field:Json(name = "number_property") var numberProperty: BigDecimal? = null,
    @Json(name = "string_property") @field:Json(name = "string_property") var stringProperty: String? = null
)
