/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 * API Version:  1.1.0
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import java.math.BigDecimal

/**
 * @property booleanProperty
 * @property integerProperty
 * @property numberProperty
 * @property stringProperty
 */
@Serializable
data class TypeResponses(
  @SerialName("boolean_property") var booleanProperty: Boolean? = null,
  @SerialName("integer_property") var integerProperty: Int? = null,
  @SerialName("number_property") var numberProperty: BigDecimal? = null,
  @SerialName("string_property") var stringProperty: String? = null

)
