/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

/**
 * @property numberMap
 * @property objectMap
 * @property stringMap
 */
@Serializable
data class XnullablePropertyMap(
    @SerialName("number_map") var numberMap: Map<String, Double?>? = null,
    @SerialName("object_map") var objectMap: JsonObject? = null,
    @SerialName("string_map") var stringMap: Map<String, String?>? = null
)
