/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.models

import com.squareup.moshi.Json
import com.yelp.codegen.generatecodesamples.tools.XNullable
import java.math.BigDecimal

/**
 *
 * @property booleanProperty
 * @property enumProperty
 * @property integerProperty
 * @property numberProperty
 * @property stringProperty
 */
data class XnullableRequiredTypeResponses(
    @Json(name = "boolean_property") @field:Json(name = "boolean_property") @XNullable var booleanProperty: Boolean? = null,
    @Json(name = "enum_property") @field:Json(name = "enum_property") @XNullable var enumProperty: XnullableRequiredTypeResponses.EnumPropertyEnum? = null,
    @Json(name = "integer_property") @field:Json(name = "integer_property") @XNullable var integerProperty: Int? = null,
    @Json(name = "number_property") @field:Json(name = "number_property") @XNullable var numberProperty: BigDecimal? = null,
    @Json(name = "string_property") @field:Json(name = "string_property") @XNullable var stringProperty: String? = null
) {
    /**
     *
     * Values: VALUE1, VALUE2
     */
    enum class EnumPropertyEnum(val value: String) {
        @Json(name = "VALUE1") VALUE1("VALUE1"),
        @Json(name = "VALUE2") VALUE2("VALUE2")
    }
}
