/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.apis

import io.reactivex.Completable
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface DefaultApi {
    /**
     * Test brackets in parameter name
     * Make sure that brackets in parameter name are treated properly
     * The endpoint is owned by junittests service owner
     * @param page (optional)
     * @param page2 (optional)
     * @param datePostedBefore (optional)
     * @param datePostedStrictlyBefore (optional)
     * @param datePostedAfter (optional)
     * @param datePostedStrictlyAfter (optional)
     */
    @Headers(
            "X-Operation-ID: getBracketsInParameterName"
    )

    @GET("/brackets/in/parameter/name")
    fun getBracketsInParameterName(
        @retrofit2.http.Query("page") page: String?,
        @retrofit2.http.Query("page[]") page2: String?,
        @retrofit2.http.Query("datePosted[before]") datePostedBefore: String?,
        @retrofit2.http.Query("datePosted[strictly_before]") datePostedStrictlyBefore: String?,
        @retrofit2.http.Query("datePosted[after]") datePostedAfter: String?,
        @retrofit2.http.Query("datePosted[strictly_after]") datePostedStrictlyAfter: String?
    ): Completable
}
