/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.apis

import io.reactivex.Completable
import okhttp3.RequestBody
import retrofit2.http.Headers
import retrofit2.http.POST

@JvmSuppressWildcards
interface FileApi {
    /**
     * The endpoint is owned by junittests service owner
     * @param file (required)
     */
    @retrofit2.http.FormUrlEncoded
    @Headers(
        "X-Operation-ID: post_file"
    )
    @POST("/post/file")
    fun postFile(
        @retrofit2.http.Field("file\"; filename=\"file") file: RequestBody
    ): Completable
}
