/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 * API Version:  1.1.0
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.apis

import io.reactivex.Completable
import okhttp3.RequestBody
import retrofit2.http.Headers
import retrofit2.http.POST

@JvmSuppressWildcards
interface FileApi {
  /**
   * The endpoint is owned by junittests service owner
   * @param clientFile (required)
   */
  @retrofit2.http.Multipart
  @Headers(
    "X-Operation-ID: post_file"
  )
  @POST("/post/file")
  fun postFile(
    @retrofit2.http.Part("client_file\"; filename=\"client_file") clientFile: RequestBody
  ): Completable
  /**
   * The endpoint is owned by junittests service owner
   * @param clientFile (required)
   */
  @retrofit2.http.FormUrlEncoded
  @Headers(
    "X-Operation-ID: post_file_without_multipart_form_data"
  )
  @POST("/post/file_without_consumes")
  @Deprecated(message = "Unsafe to use")
  fun postFileWithoutMultipartFormData(
    @retrofit2.http.Field("client_file\"; filename=\"client_file") clientFile: RequestBody
  ): Completable
  /**
   * The endpoint is owned by junittests service owner
   * @param clientFile (required)
   * @param certificateFile (required)
   */
  @retrofit2.http.Multipart
  @Headers(
    "X-Operation-ID: post_multiple_files"
  )
  @POST("/post/multiple_files")
  fun postMultipleFiles(
    @retrofit2.http.Part("client_file\"; filename=\"client_file") clientFile: RequestBody,
    @retrofit2.http.Part("certificate_file\"; filename=\"certificate_file") certificateFile: RequestBody
  ): Completable
}
