/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 * API Version:  1.1.0
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.apis

import com.yelp.codegen.generatecodesamples.models.InlineResponse200
import com.yelp.codegen.generatecodesamples.models.ModelWithOnlyTitle
import com.yelp.codegen.generatecodesamples.models.ModelWithOnlyXModel
import com.yelp.codegen.generatecodesamples.models.ModelWithXModelAndTitle
import io.reactivex.Single
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface ModelNameCheckApi {
  /**
   * The endpoint is owned by junittests service owner
   */
  @Headers(
    "X-Operation-ID: getInlinedModelWithNoNames"
  )
  @GET("/model_name/no_x-model_or_title")
  fun getInlinedModelWithNoNames(): Single<InlineResponse200>
  /**
   * The endpoint is owned by junittests service owner
   */
  @Headers(
    "X-Operation-ID: getInlinedModelWithTitleOnly"
  )
  @GET("/model_name/title_only")
  fun getInlinedModelWithTitleOnly(): Single<ModelWithOnlyTitle>
  /**
   * The endpoint is owned by junittests service owner
   */
  @Headers(
    "X-Operation-ID: getInlinedModelWithXModelAndTitle"
  )
  @GET("/model_name/x-model_and_title")
  fun getInlinedModelWithXModelAndTitle(): Single<ModelWithXModelAndTitle>
  /**
   * The endpoint is owned by junittests service owner
   */
  @Headers(
    "X-Operation-ID: getInlinedModelWithXModelOnly"
  )
  @GET("/model_name/x-model_only")
  fun getInlinedModelWithXModelOnly(): Single<ModelWithOnlyXModel>
}
