/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.apis

import com.yelp.codegen.generatecodesamples.models.Animal
import io.reactivex.Single
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface PolymorphismApi {
    /**
     * The endpoint is owned by junittests service owner
     */
    @Headers(
        "X-Operation-ID: get_check_polymorphism"
    )
    @GET("/check_polymorphism")
    fun getCheckPolymorphism(): Single<Animal>
}
