/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: JUnit Tests
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.yelp.codegen.generatecodesamples.apis

import com.yelp.codegen.generatecodesamples.models.XnullableFormatRequest
import com.yelp.codegen.generatecodesamples.models.XnullableFormatResponses
import com.yelp.codegen.generatecodesamples.models.XnullableNestedAdditionalProperties
import com.yelp.codegen.generatecodesamples.models.XnullablePropertyArray
import com.yelp.codegen.generatecodesamples.models.XnullablePropertyMap
import com.yelp.codegen.generatecodesamples.models.XnullableRequiredPropertyArray
import com.yelp.codegen.generatecodesamples.models.XnullableRequiredPropertyMap
import com.yelp.codegen.generatecodesamples.models.XnullableRequiredTypeResponses
import com.yelp.codegen.generatecodesamples.models.XnullableTypeResponses
import io.reactivex.Completable
import io.reactivex.Single
import retrofit2.http.GET
import retrofit2.http.Headers
import retrofit2.http.POST

@JvmSuppressWildcards
interface XnullableApi {
    /**
     * The endpoint is owned by junittests service owner
     * @param propertyFormat (required)
     */
    @Headers(
        "X-Operation-ID: get_xnullable_format_endpoint"
    )
    @GET("/xnullable/format_endpoint/{property_format}")
    fun getXnullableFormatEndpoint(
        @retrofit2.http.Path("property_format") propertyFormat: String
    ): Single<XnullableFormatResponses>
    /**
     * The endpoint is owned by junittests service owner
     */
    @Headers(
        "X-Operation-ID: get_xnullable_nested_additional_properties"
    )
    @GET("/xnullable/nested_additional_properties")
    fun getXnullableNestedAdditionalProperties(): Single<XnullableNestedAdditionalProperties>
    /**
     * The endpoint is owned by junittests service owner
     * @param valueType (required)
     * @param size (required)
     */
    @Headers(
        "X-Operation-ID: get_xnullable_property_array"
    )
    @GET("/xnullable/property_array/{value_type}/{size}")
    fun getXnullablePropertyArray(
        @retrofit2.http.Path("value_type") valueType: String,
        @retrofit2.http.Path("size") size: String
    ): Single<XnullablePropertyArray>
    /**
     * The endpoint is owned by junittests service owner
     * @param valueType (required)
     * @param size (required)
     */
    @Headers(
        "X-Operation-ID: get_xnullable_property_map"
    )
    @GET("/xnullable/property_map/{value_type}/{size}")
    fun getXnullablePropertyMap(
        @retrofit2.http.Path("value_type") valueType: String,
        @retrofit2.http.Path("size") size: String
    ): Single<XnullablePropertyMap>
    /**
     * The endpoint is owned by junittests service owner
     * @param size (required)
     */
    @Headers(
        "X-Operation-ID: get_xnullable_required_property_array"
    )
    @GET("/xnullable/required/property_array/{size}")
    fun getXnullableRequiredPropertyArray(
        @retrofit2.http.Path("size") size: String
    ): Single<XnullableRequiredPropertyArray>
    /**
     * The endpoint is owned by junittests service owner
     * @param size (required)
     */
    @Headers(
        "X-Operation-ID: get_xnullable_required_property_map"
    )
    @GET("/xnullable/required/property_map/{size}")
    fun getXnullableRequiredPropertyMap(
        @retrofit2.http.Path("size") size: String
    ): Single<XnullableRequiredPropertyMap>
    /**
     * The endpoint is owned by junittests service owner
     * @param propertyType (required)
     */
    @Headers(
        "X-Operation-ID: get_xnullable_required_type_endpoint"
    )
    @GET("/xnullable/required/type_endpoint/{property_type}")
    fun getXnullableRequiredTypeEndpoint(
        @retrofit2.http.Path("property_type") propertyType: String
    ): Single<XnullableRequiredTypeResponses>
    /**
     * The endpoint is owned by junittests service owner
     * @param propertyType (required)
     */
    @Headers(
        "X-Operation-ID: get_xnullable_type_endpoint"
    )
    @GET("/xnullable/type_endpoint/{property_type}")
    fun getXnullableTypeEndpoint(
        @retrofit2.http.Path("property_type") propertyType: String
    ): Single<XnullableTypeResponses>
    /**
     * The endpoint is owned by junittests service owner
     * @param propertyFormat (required)
     */
    @Headers(
        "X-Operation-ID: post_xnullable_format_endpoint"
    )
    @POST("/xnullable/format_endpoint/{property_format}")
    fun postXnullableFormatEndpoint(
        @retrofit2.http.Body propertyFormat: XnullableFormatRequest
    ): Completable
}
